### PR TITLE
Fix mix command line calls in README.md

### PR DESCRIPTION
**Pull request by rrrene**
This is coming along nicely :+1:

One thing I noticed: It seems to me these command line calls are off, as there is no `mix cachex` task after cloning and compiling the project.

### CODE REVIEW

**Comment by zackehh** [comment]
@rrrene thanks :)

However... there *is* a `mix cachex` task, are you sure you're on the latest master? I just tried a fresh clone and it was fine.

```bash
$ cd /tmp
$ git clone git@github.com:zackehh/cachex.git
$ cd cachex
$ mix deps.get
$ mix cachex test
```

The changes to the commands you make wouldn't run because Cachex requires slave nodes started before any test runs.

Can you give it another shot?

**Comment by rrrene** [comment]
Ah, my bad, was before my fist coffee :(

In my defense: `mix cachex` does not show up in `mix -h`

**Comment by zackehh** [comment]
@rrrene no problem!

Is there some trick to getting it to show up with `mix -h`? I've tried this before and noticed that it's not included.

**Comment by rrrene** [comment]
Add a `@shortdoc` to the module: https://github.com/rrrene/inch_ex/blob/master/lib/mix/tasks/inch.ex

**Pull request closed without merging**
